let RELICS = [];
let PRICES = {}; // key: item display name -> plat integer

const rarityToLabel = (r) => {
  if (typeof r === "number") return ["Common","Uncommon","Rare"][r] ?? String(r);
  const s = String(r).toLowerCase();
  if (s.includes("common")) return "Common";
  if (s.includes("uncommon")) return "Uncommon";
  if (s.includes("rare")) return "Rare";
  return String(r);
};

function norm(s){ return (s||"").trim().toLowerCase(); }

function relicDisplayName(relicObj){
  const era = relicObj.era ?? relicObj.tier ?? "";
  const name = relicObj.name ?? relicObj.relicName ?? relicObj.code ?? "";
  return `${era} ${name}`.trim().replace(/\s+/g, " ");
}

function getRelicByDisplay(display){
  const n = norm(display);
  return RELICS.find(r => norm(relicDisplayName(r)) === n) || null;
}

function platForItem(itemName){
  const v = PRICES[itemName];
  return (typeof v === "number") ? v : null;
}

function setStatus(msg){
  document.getElementById("status").textContent = msg || "";
}

function renderRows(relicsPicked){
  const rowsEl = document.getElementById("rows");
  rowsEl.innerHTML = "";

  const all = [];
  for (const r of relicsPicked){
    const drops = r.drops ?? r.rewards ?? [];
    for (const d of drops){
      const item = d.item ?? d.name ?? d.reward ?? "Unknown";
      const rarity = d.rarity ?? d.tier ?? d.chance ?? "";
      const plat = platForItem(item);
      all.push({
        item,
        from: relicDisplayName(r),
        rarity: rarityToLabel(rarity),
        plat: plat ?? -1
      });
    }
  }

  // Merge duplicates
  const merged = new Map();
  for (const e of all){
    const key = e.item;
    const prev = merged.get(key);
    if (!prev){
      merged.set(key, { ...e, fromSet: new Set([e.from]) });
    } else {
      prev.fromSet.add(e.from);
      prev.plat = Math.max(prev.plat, e.plat);
    }
  }

  const final = [...merged.values()].map(x => ({
    item: x.item,
    from: [...x.fromSet].join(", "),
    rarity: x.rarity,
    plat: x.plat
  }));

  final.sort((a,b) => (b.plat - a.plat));

  for (const e of final){
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${e.item}</td>
      <td class="muted">${e.from}</td>
      <td class="muted">${e.rarity}</td>
      <td class="num">${e.plat >= 0 ? e.plat : "?"}</td>
    `;
    rowsEl.appendChild(tr);
  }

  setStatus(`Showing ${final.length} unique rewards`);
}

async function boot(){
  setStatus("Loading data…");

  // These files will be generated by the GitHub Action at deploy-time
  const [relicRes, priceRes] = await Promise.all([
    fetch("./data/Relics.min.json", { cache: "no-store" }),
    fetch("./data/prices.json", { cache: "no-store" })
  ]);

  RELICS = await relicRes.json();
  PRICES = await priceRes.json();

  const dl = document.getElementById("relicsList");
  dl.innerHTML = "";
  const names = RELICS.map(relicDisplayName).sort((a,b)=>a.localeCompare(b));
  for (const n of names){
    const opt = document.createElement("option");
    opt.value = n;
    dl.appendChild(opt);
  }

  document.getElementById("footer").textContent =
    `Relics: ${RELICS.length} • Price entries: ${Object.keys(PRICES).length}`;

  setStatus("Ready");
}

document.getElementById("btnShow").addEventListener("click", () => {
  const picks = ["r1","r2","r3","r4"].map(id => document.getElementById(id).value);
  const relics = picks.map(getRelicByDisplay).filter(Boolean);

  if (relics.length === 0){
    setStatus("Pick at least 1 valid relic");
    return;
  }
  renderRows(relics);
});

document.getElementById("btnClear").addEventListener("click", () => {
  ["r1","r2","r3","r4"].forEach(id => document.getElementById(id).value = "");
  document.getElementById("rows").innerHTML = "";
  setStatus("Cleared");
});

boot().catch(err => {
  console.error(err);
  setStatus("Failed to load data (wait for first deploy to finish)");
});